name: Sincronizar con Tigre Automáticamente
on:
  schedule:
    - cron: '0 8 * * *' # Se ejecutará solo todas las mañanas
  workflow_dispatch:   # Te permite activarlo tú cuando quieras

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configurar Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Traer cambios de Tigre
        run: |
          git remote add upstream https://github.com/TIGRE9725/guia.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Sincronización automática"
          git push origin main
